### ISSUE TITLE
sbt-robovm does not work on Windows, even if not used in multi-project settings

### ISSUE THREAD

**Issue by aginiewicz** [roboscala/sbt-robovm#10]
Adding sbt-robovm plugin causes SBT to fail with information "Unsupported Operating System: Windows ***" even in multi-project setups (like libgdx-sbt-project.g8), when someone compiles only Windows or Android versions.

**Comment by Darkyenus** [comment]
Is this still an issue?

**Comment by ajhager** [comment]
I have not done anything in particular to fix it, so it needs testing. I have a windows dev machine again so I can try it.

**Comment by Darkyenus** [comment]
If I understand this correctly, just including sbt-robovm in build will produce errors on sbt run in windows, is that correct?

**Comment by ajhager** [comment]
Yeah, for example in the sbt libgdx template. We will want it to detect if it is being run on an unsupported platform and make sure to not doing anything.

**Comment by aginiewicz** [comment]
A fellow windows user tried libgdx sbt template, the message change since last time. It is now

```
java.lang.UnsatisfiedLinkError: Native library for windows-x86_64 not found
```
(full stack trace: http://pastebin.com/t4WbFtw5) and earlier it was
```
Unsupported Operating System: Windows ***
```

**Comment by Darkyenus** [comment]
Hmm, it seems that this line `val config = launchTask(Arch.getDefaultArch, OS.getDefaultOS, TargetType.console, skipInstall = true).value` has its parameters evaluated even without calling the task. That seems to be a property of `.value` macro. When I have a little time to setup test environment, I'll try fixing it by changing launchTask to pass parameters by name (` arch: =>Arch, ...`), that could hopefully fix it.

**Comment by ajhager** [comment]
I will test this when I update the libgdx g8 template.

**Comment by ajhager** [comment]
This should be fixed.
