### ISSUE TITLE
'Launching RoboVM app' does not end until the app is closed

### ISSUE THREAD

**Issue by jvliwanag** [roboscala/sbt-robovm#11]
While doing 'sbt iphone-sim', the 'Launching RoboVM app' stage doesn't stop until the app is closed from the simulator. I believe the task should end once the app has already been launched.

It's awesome to see 'sbt ~iphone-sim' to be working nicely though. The only minor catch is I have to close the app to launch the updated version.

Tried this on the scala-ios-demos.

**Comment by ajhager** [comment]
This still needs work. Running the app on device or simulator should not block sbt.

**Comment by Darkyenus** [comment]
I disagree, it should block sbt, but only if the stdin/err are connected to the app. And this works (usually; sometimes it doesn't, but that might have been in the older versions of RoboVM). Maybe we can add option to not block, but the main purpose of blocking is to show output of the app. Which is very important during debugging (especially when the debugger is behind a paywall).

Btw. running java/scala project with standard `sbt run` DOES block sbt to show output, so I'd argue that this should too.

**Comment by ajhager** [comment]
You have convinced me.
