### ISSUE TITLE
Bring more visibility to sbt-robovm by pull request to sbt website

### ISSUE THREAD

**Issue by aginiewicz** [roboscala/sbt-robovm#20]
I believe that by providing pull request to https://github.com/sbt/website this project can be included in list of community SBT plugins, it should bring more visibility, because there is no iOS development plugin there, and two Android plugins on https://github.com/sbt/website/blob/HEAD/src/reference/01-General-Info/02-Community-Plugins.md#android-plugin

**Comment by ajhager** [comment]
It looks like awesome-scala has been pretty active lately, but it seems like we might need to actually submit a PR instead of just an issue.

**Comment by ajhager** [comment]
Will be fixed in #37
