### ISSUE TITLE
 Adding almost any code to the hello demo breaks the robovm compilation for iOS.

### ISSUE THREAD

**Issue by windemut** [roboscala/sbt-robovm#26]
I have posted this over at the scala-ios-demos in more detail (https://github.com/roboscala/scala-ios-demos/issues/1). Not sure anyone's listening there, so mention it here. It seems strange that you all appear to be not affected by it.

I am trying to use sbt-robovm to run the scala demo apps on the IOS simulator.

I have gotten the "empty" and "hello" demos running just fine, using the iphone-sim target. However, when I try to add more code, I get messages such as

Warning: scala.math.BigDecimal$$anonfun$equals$1 is a phantom class!
(A varying number of different classes, depending on what code is added)

followed by

LLVM ERROR: ran out of registers during register allocation

Strenuous googling has convinced me that there is a stubborn issue in LLVM 3.4 that causes the latter error in roboVM for any code that references Predef. The "empty" and "hello" demos appear to be simple enough that they don't, but adding almost any Scala code to them triggers the error. Notably, a string concatenation such as ("Click #"+clickCount) seems to set it off, among many other things. The best location to track this error I found is here: https://github.com/robovm/robovm/issues/313.

Perhaps the easiest question I have is why has no-one working with sbt-robovm observed this issue, apparently? Is no-one using the iphone-sim target or is no-one compiling anything other than the demos? Or, most likely, is there something I am overlooking? Absent a simple explanation, perhaps someone could give it a quick try by replacing "Hello, Robo" with "Hello Robo "+1, to see if the error reproduces in hands other than mine.

It is a shame, it would be really nice to be able to do IOS using Scala. As it is, there appears to be no way, at least until they fix that LLVM bug.

Thanks!

**Comment by ntherning** [comment]
We just released a new version of RoboVM which is based on LLVM trunk and uses `penryn` as CPU when building for x86/x86_64. I believe that this will take care of the problem we have had when compiling x86 (32-bit) apps. Please try with the beta-02 release without the workaround or give me instructions on how to test this myself. Thanks!

**Comment by Darkyenus** [comment]
Compiling previously crashing class (ForkJoinPool) now (beta-02) seems to work. Tested using "ios x86 release" configuration. Thank you very much!
