### ISSUE TITLE
Clean up internal code

### ISSUE THREAD

**Issue by Darkyenus** [roboscala/sbt-robovm#27]
I want to change some things, but I'm not sure whether it is a good idea, so I want to ask first.

Since (Ios)BuildSettings classes are just wrappers for task results that can now be called inside launchTask method directly, do we still need them? They are hidden from api, so they just add some layer of complexity, which I am not sure is needed.

**Comment by ajhager** [comment]
Can this be closed now that your changes have been merged?

**Comment by Darkyenus** [comment]
Yeah, this issue is now outdated.
