### ISSUE TITLE
Automatically download robovm-X.Y.Z.tar.gz

### ISSUE THREAD

**Issue by ntherning** [roboscala/sbt-robovm#28]
The maven and gradle plugins do this already. This is dead simple now since we added the `robovm-maven-resolver` artifact. Here's how to:

```java
  RoboVMResolver resolver = new RoboVMResolver();
  File dir = resolver.resolveAndUnpackRoboVMDistArtifact("1.0.0-alpha-04");
```

This will download the `robovm-dist` artifact with the specified version from Maven Central and unpack it into the local Maven repository and return the path to it. If this has already been done it does nothing.

The resolver will be included in the next RoboVM release.

**Comment by ajhager** [comment]
Fixed in 7c4ea6a085062fd04e89689a86763ae4f4cf3c71.
