### ISSUE TITLE
fork

### ISSUE THREAD

**Issue by gedw99** [roboscala/sbt-robovm#31]
Is this project dead ??

I would be happy to contribute but done sees any action on this repo.

**Comment by ajhager** [comment]
I have actually just started a bit of a rewrite, but in the mean time there has been a lot of activity at https://github.com/Darkyenus/sbt-robovm. I would suggest checking that fork out.

**Comment by Darkyenus** [comment]
@ajhager Will any of my code be useful for your rewrite? (Check especially branch "cleanup") I'll be happy to help.

**Comment by mseddon** [comment]
@Darkyenus thanks for that, it's keeping things vaguely sensible!  I wonder if you wouldn't mind publishing it to bintray somewhere?  Also, if you could enable issues on your fork, that would be handy, since I am really not sure what's happening with this project any more.

**Comment by Darkyenus** [comment]
@mseddon I didn't realize they were disabled by default - enabled! I'll look into publishing it soon (when I'll have some time).

**Comment by ajhager** [comment]
The changes of @Darkyenus have been merge in 7c4ea6a085062fd04e89689a86763ae4f4cf3c71, so this should be fixed with the next release.

**Comment by mseddon** [comment]
:+1 that is excellent news, thanks!
