### ISSUE TITLE
Clean up README and add docs for all new features

### ISSUE THREAD

**Issue by ajhager** [roboscala/sbt-robovm#37]
- [x] Debugging
- [x] Getting SNAPSHOT and normal builds
- [x] Detailed docs for each command
- [x] Do awesome-scala PR

**Comment by Darkyenus** [comment]
Awesome-scala already lists sbt-robovm ([link](https://github.com/lauris/awesome-scala/issues/106))

**Comment by ajhager** [comment]
@Darkyenus I know the README / docs will not a lot more love, but could you please test master locally for me and proof the README?

**Comment by Darkyenus** [comment]
I have actually managed to rewrite the README, for now I have pushed it only into mine [fork](https://github.com/Darkyenus/sbt-robovm), so you can check it out. It should be much more helpful than what we have now, but it still needs some work.

I don't have time and energy to keep improving it today, but if you feel like it, you can merge it.

Mental TODO: SBT now allows multi-project builds defined in .sbt files, yet the readme still suggests .scala buuild files, test if it works in .sbt and change the readme (and samples) accordingly
_(More elaborate issue is narrowly connected with this: It it worthwhile to essentialy fake the project types only to insert a few keys? Woudn't it be better to get rid of the whole project system and just supply relevant key settings in Seq[]'s to be added to the build definition, like other projects do?)_

**Comment by ajhager** [comment]
Your README looks great! I will go through it a couple of times and merge it. Thanks for your hard work.

**Comment by ajhager** [comment]
The docs will continue to improve, but closed by 7afd0dd2b6ceacdb691999e4267db021fd26e583
