### ISSUE TITLE
And new publishing support and travis build for -SNAPSHOTs

### ISSUE THREAD

**Issue by ajhager** [roboscala/sbt-robovm#39]

**Comment by Darkyenus** [comment]
I have been playing around Jitpack a bit, it seems to work great, but it has a small caveat - it does not seem to support sbt cross building (that is building for different scala versions and appending (for example) `_2.10` to artifact id. This may cause problems when different scala versions are used. One workaround I have seen, is to change build version, create commit and tag it with project version **and** scala version and then repeat for other scala versions. This however, is messy and too much work. So I propose keeping jitpack builds as snapshots on one default scala version and doing proper releases with cross building to the sbt plugin repo every RoboVM version.

**Comment by ajhager** [comment]
I have settled on using travis to automatically publish SNAPSHOT builds instead of using jitpack. Then I will manually publish stable builds , syncing releases with releases of RoboVM.

**Comment by ajhager** [comment]
Fixed by 14f8edcd6387e26a3be6efd679e3b722cb69716d
