### ISSUE TITLE
1.6.0 support

### ISSUE THREAD

**Issue by ScalaWilliam** [roboscala/sbt-robovm#43]
1.6.0 just came out.

**Comment by ajhager** [comment]
I am working on testing for 1.6.0. I will be doing coordinated releases with RoboVM from now on.

**Comment by Darkyenus** [comment]
@ajhager Any progress? I have started working on this and I'm in the phase of trying to understand what actually changed and how, since the changes don't seem to be trivial. I'll assign it to myself in the meantime, but feel free to reassign to yourself if you come up with a patch sooner.

**Comment by ajhager** [comment]
Thanks @Darkyenus. I immediately had to travel for almost two weeks. Testing your PR, and then I'll do the README update and do a release for 1.6.

**Comment by Darkyenus** [comment]
Funnily enough, I have just started rewriting the readme. Should I continue or will you take care of it?

**Comment by ajhager** [comment]
Feel free to update the README, but no pressure. I am working on the new setup for publishing releases.
