### ISSUE TITLE
Executable size

### ISSUE THREAD

**Issue by joprice** [roboscala/sbt-robovm#64]
Running the 'hello' example gives me an executable of 76M. This doesn't give much room until apple's 100m wireless download limit. I turned on the aggressive treeShaker, but I got the exact same executable. Is the treeShaker not used when running the `iphoneSim` task?

```
4.0K    target/robovm.tmp/robo-vm-test.app/Info.plist
 60K    target/robovm.tmp/robo-vm-test.app/lib/boot/robovm-rt.jar
 60K    target/robovm.tmp/robo-vm-test.app/lib/boot
4.0K    target/robovm.tmp/robo-vm-test.app/lib/classes0.jar
 16K    target/robovm.tmp/robo-vm-test.app/lib/robovm-cocoatouch-1.13.0.jar
4.0K    target/robovm.tmp/robo-vm-test.app/lib/robovm-objc-1.13.0.jar
8.0K    target/robovm.tmp/robo-vm-test.app/lib/scala-library-2.11.7.jar
 92K    target/robovm.tmp/robo-vm-test.app/lib
 76M    target/robovm.tmp/robo-vm-test.app/robo-vm-test
 76M    target/robovm.tmp/robo-vm-test.app
```

**Comment by Darkyenus** [comment]
If you are running in 32bit mode (which is default IIRC), the tree shaker does not run "due to bug in linker", this is a RoboVM bug, you should find that in the logs. That, combined with heavy scala-library contributes to pretty big executables. You can always use proguard though.

**Comment by joprice** [comment]
That tip helped!

``` scala
 robovmTarget64bit := true
```

```
4.0K    target/robovm.tmp/robo-vm-test.app/Info.plist
 60K    target/robovm.tmp/robo-vm-test.app/lib/boot/robovm-rt.jar
 60K    target/robovm.tmp/robo-vm-test.app/lib/boot
4.0K    target/robovm.tmp/robo-vm-test.app/lib/classes0.jar
 16K    target/robovm.tmp/robo-vm-test.app/lib/robovm-cocoatouch-1.13.0.jar
4.0K    target/robovm.tmp/robo-vm-test.app/lib/robovm-objc-1.13.0.jar
8.0K    target/robovm.tmp/robo-vm-test.app/lib/scala-library-2.11.7.jar
 92K    target/robovm.tmp/robo-vm-test.app/lib
 39M    target/robovm.tmp/robo-vm-test.app/robo-vm-test
 39M    target/robovm.tmp/robo-vm-test.app
```

Perhaps this should be mentioned in the readme?

**Comment by joprice** [comment]
Do you know of an example sbt-rovovm ios proguard project?

**Comment by Darkyenus** [comment]
I can't think of any, but it shouldn't be hard. Simply configure [sbt-proguard plugin](https://github.com/sbt/sbt-proguard) and plug it into the RoboVM plugin with something like:

```
robovmInputJars := (proguard in Proguard).value
```
